- name: add user and create ssh key  
  user: name={{ deploy_user }} shell=/bin/bash groups=rvm append=true
- name: Create authorized_keys for user
  authorized_key: user={{ deploy_user }} key=https://github.com/{{ gh_pubkey_user }}.keys
- name: Add user to sudoers
  lineinfile:
    "dest=/etc/sudoers
    regexp='^{{ deploy_user }} ALL'
    line='{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL'
    state=present"
- name: Creates deploy_directory directory
  file: path={{ deploy_directory }} state=directory owner=bholt group=www-data mode=0775
- name: Install libraries
  apt: name={{ item }} state=present
  with_items:
    - libxslt-dev
    - libxml2-dev	
    - libmysqlclient-dev
    - imagemagick